// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewAdder creates a new instance of Adder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Adder {
	mock := &Adder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Adder is an autogenerated mock type for the Adder type
type Adder struct {
	mock.Mock
}

type Adder_Expecter struct {
	mock *mock.Mock
}

func (_m *Adder) EXPECT() *Adder_Expecter {
	return &Adder_Expecter{mock: &_m.Mock}
}

// SingleDigitAdd provides a mock function for the type Adder
func (_mock *Adder) SingleDigitAdd(x int, y int) (int, error) {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for SingleDigitAdd")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) (int, error)); ok {
		return returnFunc(x, y)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = returnFunc(x, y)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(x, y)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Adder_SingleDigitAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SingleDigitAdd'
type Adder_SingleDigitAdd_Call struct {
	*mock.Call
}

// SingleDigitAdd is a helper method to define mock.On call
//   - x int
//   - y int
func (_e *Adder_Expecter) SingleDigitAdd(x interface{}, y interface{}) *Adder_SingleDigitAdd_Call {
	return &Adder_SingleDigitAdd_Call{Call: _e.mock.On("SingleDigitAdd", x, y)}
}

func (_c *Adder_SingleDigitAdd_Call) Run(run func(x int, y int)) *Adder_SingleDigitAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Adder_SingleDigitAdd_Call) Return(n int, err error) *Adder_SingleDigitAdd_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Adder_SingleDigitAdd_Call) RunAndReturn(run func(x int, y int) (int, error)) *Adder_SingleDigitAdd_Call {
	_c.Call.Return(run)
	return _c
}
