// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewInventoryChecker creates a new instance of InventoryChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryChecker {
	mock := &InventoryChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryChecker is an autogenerated mock type for the InventoryChecker type
type InventoryChecker struct {
	mock.Mock
}

type InventoryChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryChecker) EXPECT() *InventoryChecker_Expecter {
	return &InventoryChecker_Expecter{mock: &_m.Mock}
}

// CheckInventory provides a mock function for the type InventoryChecker
func (_mock *InventoryChecker) CheckInventory(context1 context.Context, uUID uuid.UUID, n int32) (bool, error) {
	ret := _mock.Called(context1, uUID, n)

	if len(ret) == 0 {
		panic("no return value specified for CheckInventory")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32) (bool, error)); ok {
		return returnFunc(context1, uUID, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32) bool); ok {
		r0 = returnFunc(context1, uUID, n)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32) error); ok {
		r1 = returnFunc(context1, uUID, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryChecker_CheckInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckInventory'
type InventoryChecker_CheckInventory_Call struct {
	*mock.Call
}

// CheckInventory is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
//   - n int32
func (_e *InventoryChecker_Expecter) CheckInventory(context1 interface{}, uUID interface{}, n interface{}) *InventoryChecker_CheckInventory_Call {
	return &InventoryChecker_CheckInventory_Call{Call: _e.mock.On("CheckInventory", context1, uUID, n)}
}

func (_c *InventoryChecker_CheckInventory_Call) Run(run func(context1 context.Context, uUID uuid.UUID, n int32)) *InventoryChecker_CheckInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InventoryChecker_CheckInventory_Call) Return(b bool, err error) *InventoryChecker_CheckInventory_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *InventoryChecker_CheckInventory_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID, n int32) (bool, error)) *InventoryChecker_CheckInventory_Call {
	_c.Call.Return(run)
	return _c
}
